-- KP Hauling & Dumpster Services Supabase setup
-- Safe for a shared Supabase project: all app tables are prefixed with kp_hauling_.
-- Run this in Supabase SQL Editor after creating the owner Auth user:
--   email: admin@kp.local
--   password: admin123

create extension if not exists pgcrypto;

do $$ begin
  create type public.kp_hauling_user_role as enum ('owner', 'admin', 'driver');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_availability_status as enum ('Available', 'Unavailable', 'On Call');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_dumpster_status as enum ('Available', 'Scheduled Drop-Off', 'Delivered', 'Pickup Needed', 'Overdue', 'In Transit', 'Out of Service');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_job_status as enum ('Scheduled Drop-Off', 'Delivered', 'Pickup Needed', 'Overdue', 'Picked Up / Completed');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_payment_status as enum ('Unpaid', 'Deposit Paid', 'Paid', 'Invoice Sent', 'Past Due');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_dumpster_size as enum ('10 yd', '15 yd', '20 yd', '30 yd');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_dumpster_type as enum ('Roll-off', 'Concrete', 'Yard Waste', 'Mixed Debris');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_truck_type as enum ('Company Truck', 'Personal Truck');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_payment_method as enum ('Cash', 'Card', 'Check', 'Other');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.kp_hauling_route_type as enum ('delivery', 'pickup');
exception when duplicate_object then null;
end $$;

create table if not exists public.kp_hauling_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role public.kp_hauling_user_role not null default 'driver',
  phone text,
  availability_status public.kp_hauling_availability_status not null default 'Unavailable',
  availability_notes text,
  availability_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_driver_availability_windows (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.kp_hauling_profiles(id) on delete cascade,
  available_date date not null,
  start_time time not null,
  end_time time not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kp_hauling_availability_valid_time check (start_time < end_time)
);

create table if not exists public.kp_hauling_dumpsters (
  id uuid primary key default gen_random_uuid(),
  number text not null unique,
  size public.kp_hauling_dumpster_size not null,
  type public.kp_hauling_dumpster_type not null default 'Roll-off',
  status public.kp_hauling_dumpster_status not null default 'Available',
  current_location text not null default 'KP yard',
  current_address text not null default '',
  current_customer text,
  current_job_id uuid,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_jobs (
  id uuid primary key default gen_random_uuid(),
  job_number bigint generated by default as identity unique,
  customer_name text not null,
  phone text not null default '',
  email text not null default '',
  job_address text not null,
  dumpster_id uuid references public.kp_hauling_dumpsters(id) on delete set null,
  dumpster_number text,
  dumpster_size public.kp_hauling_dumpster_size not null,
  delivery_driver_id uuid references public.kp_hauling_profiles(id) on delete set null,
  delivery_driver_name text,
  delivery_dispatch_date date,
  delivery_dispatch_notes text,
  delivery_truck_type public.kp_hauling_truck_type,
  delivery_completed_at time,
  delivery_completion_notes text,
  delivery_driver_paid_at date,
  delivery_driver_pay_amount numeric(10,2),
  delivery_driver_pay_notes text,
  pickup_driver_id uuid references public.kp_hauling_profiles(id) on delete set null,
  pickup_driver_name text,
  pickup_dispatch_date date,
  pickup_dispatch_notes text,
  pickup_truck_type public.kp_hauling_truck_type,
  pickup_completed_at time,
  pickup_completion_notes text,
  pickup_driver_paid_at date,
  pickup_driver_pay_amount numeric(10,2),
  pickup_driver_pay_notes text,
  starting_dumpster_address text,
  estimated_one_way_miles numeric(10,1),
  delivery_return_miles numeric(10,1),
  pickup_destination_address text default 'KP yard',
  pickup_one_way_miles numeric(10,1),
  pickup_return_miles numeric(10,1),
  drop_off_date date not null,
  drop_off_time time,
  rental_length_days integer not null default 7,
  expected_pickup_date date not null,
  expected_pickup_time time,
  actual_pickup_date date,
  price numeric(10,2) not null default 0,
  payment_status public.kp_hauling_payment_status not null default 'Unpaid',
  status public.kp_hauling_job_status not null default 'Scheduled Drop-Off',
  job_notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kp_hauling_dumpsters
  drop constraint if exists kp_hauling_dumpsters_current_job_id_fkey;

alter table public.kp_hauling_dumpsters
  add constraint kp_hauling_dumpsters_current_job_id_fkey
  foreign key (current_job_id) references public.kp_hauling_jobs(id) on delete set null;

create table if not exists public.kp_hauling_job_charges (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.kp_hauling_jobs(id) on delete cascade,
  label text not null,
  amount numeric(10,2) not null check (amount >= 0),
  charge_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_job_payments (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.kp_hauling_jobs(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  payment_date date not null default current_date,
  note text not null default '',
  method public.kp_hauling_payment_method default 'Other',
  driver_id uuid references public.kp_hauling_profiles(id) on delete set null,
  driver_name text,
  collected_during public.kp_hauling_route_type,
  created_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_expenses (
  id uuid primary key default gen_random_uuid(),
  expense_date date not null default current_date,
  label text not null,
  amount numeric(10,2) not null check (amount >= 0),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_driver_cash_handoffs (
  id uuid primary key default gen_random_uuid(),
  handoff_date date not null default current_date,
  driver_id uuid references public.kp_hauling_profiles(id) on delete set null,
  driver_name text not null,
  amount numeric(10,2) not null check (amount >= 0),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_owner_notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  detail text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.kp_hauling_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.kp_hauling_profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  notify_dispatch boolean not null default true,
  notify_pickup_due boolean not null default true,
  notify_driver_updates boolean not null default true,
  notify_availability boolean not null default true,
  daily_reminder_time time not null default '07:00',
  reminder_timezone text not null default 'America/Chicago',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kp_hauling_push_subscriptions
  add column if not exists daily_reminder_time time not null default '07:00';

alter table public.kp_hauling_push_subscriptions
  add column if not exists reminder_timezone text not null default 'America/Chicago';

create table if not exists public.kp_hauling_due_reminder_sends (
  id uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references public.kp_hauling_push_subscriptions(id) on delete cascade,
  user_id uuid not null references public.kp_hauling_profiles(id) on delete cascade,
  reminder_date date not null,
  created_at timestamptz not null default now(),
  unique (subscription_id, reminder_date)
);

create or replace function public.kp_hauling_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.kp_hauling_profiles
    where id = auth.uid()
      and role in ('owner', 'admin')
  );
$$;

alter table public.kp_hauling_profiles enable row level security;
alter table public.kp_hauling_driver_availability_windows enable row level security;
alter table public.kp_hauling_dumpsters enable row level security;
alter table public.kp_hauling_jobs enable row level security;
alter table public.kp_hauling_job_charges enable row level security;
alter table public.kp_hauling_job_payments enable row level security;
alter table public.kp_hauling_expenses enable row level security;
alter table public.kp_hauling_driver_cash_handoffs enable row level security;
alter table public.kp_hauling_owner_notifications enable row level security;
alter table public.kp_hauling_push_subscriptions enable row level security;
alter table public.kp_hauling_due_reminder_sends enable row level security;

drop policy if exists "KP profiles are visible to logged in users" on public.kp_hauling_profiles;
create policy "KP profiles are visible to logged in users"
on public.kp_hauling_profiles for select
to authenticated
using (true);

drop policy if exists "KP admins manage profiles" on public.kp_hauling_profiles;
create policy "KP admins manage profiles"
on public.kp_hauling_profiles for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP drivers update own profile" on public.kp_hauling_profiles;
create policy "KP drivers update own profile"
on public.kp_hauling_profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "KP users read availability" on public.kp_hauling_driver_availability_windows;
create policy "KP users read availability"
on public.kp_hauling_driver_availability_windows for select
to authenticated
using (true);

drop policy if exists "KP drivers manage own availability" on public.kp_hauling_driver_availability_windows;
create policy "KP drivers manage own availability"
on public.kp_hauling_driver_availability_windows for all
to authenticated
using (driver_id = auth.uid() or public.kp_hauling_is_admin())
with check (driver_id = auth.uid() or public.kp_hauling_is_admin());

drop policy if exists "KP admins manage dumpsters" on public.kp_hauling_dumpsters;
create policy "KP admins manage dumpsters"
on public.kp_hauling_dumpsters for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP drivers read assigned and open jobs" on public.kp_hauling_jobs;
create policy "KP drivers read assigned and open jobs"
on public.kp_hauling_jobs for select
to authenticated
using (
  public.kp_hauling_is_admin()
  or delivery_driver_id = auth.uid()
  or pickup_driver_id = auth.uid()
  or (status = 'Scheduled Drop-Off' and delivery_driver_id is null)
  or (status in ('Delivered', 'Pickup Needed', 'Overdue') and pickup_driver_id is null)
);

drop policy if exists "KP admins manage jobs" on public.kp_hauling_jobs;
create policy "KP admins manage jobs"
on public.kp_hauling_jobs for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP drivers update assigned jobs" on public.kp_hauling_jobs;
create policy "KP drivers update assigned jobs"
on public.kp_hauling_jobs for update
to authenticated
using (delivery_driver_id = auth.uid() or pickup_driver_id = auth.uid())
with check (delivery_driver_id = auth.uid() or pickup_driver_id = auth.uid());

drop policy if exists "KP users read job money rows" on public.kp_hauling_job_charges;
create policy "KP users read job money rows"
on public.kp_hauling_job_charges for select
to authenticated
using (true);

drop policy if exists "KP admins manage job charges" on public.kp_hauling_job_charges;
create policy "KP admins manage job charges"
on public.kp_hauling_job_charges for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP users read payments" on public.kp_hauling_job_payments;
create policy "KP users read payments"
on public.kp_hauling_job_payments for select
to authenticated
using (true);

drop policy if exists "KP admins and assigned drivers add payments" on public.kp_hauling_job_payments;
create policy "KP admins and assigned drivers add payments"
on public.kp_hauling_job_payments for insert
to authenticated
with check (
  public.kp_hauling_is_admin()
  or driver_id = auth.uid()
);

drop policy if exists "KP admins manage payments" on public.kp_hauling_job_payments;
create policy "KP admins manage payments"
on public.kp_hauling_job_payments for update
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP admins delete payments" on public.kp_hauling_job_payments;
create policy "KP admins delete payments"
on public.kp_hauling_job_payments for delete
to authenticated
using (public.kp_hauling_is_admin());

drop policy if exists "KP admins manage expenses" on public.kp_hauling_expenses;
create policy "KP admins manage expenses"
on public.kp_hauling_expenses for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP admins manage cash handoffs" on public.kp_hauling_driver_cash_handoffs;
create policy "KP admins manage cash handoffs"
on public.kp_hauling_driver_cash_handoffs for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP users read notifications" on public.kp_hauling_owner_notifications;
create policy "KP users read notifications"
on public.kp_hauling_owner_notifications for select
to authenticated
using (public.kp_hauling_is_admin());

drop policy if exists "KP admins manage notifications" on public.kp_hauling_owner_notifications;
create policy "KP admins manage notifications"
on public.kp_hauling_owner_notifications for all
to authenticated
using (public.kp_hauling_is_admin())
with check (public.kp_hauling_is_admin());

drop policy if exists "KP users manage own push subscriptions" on public.kp_hauling_push_subscriptions;
create policy "KP users manage own push subscriptions"
on public.kp_hauling_push_subscriptions for all
to authenticated
using (user_id = auth.uid() or public.kp_hauling_is_admin())
with check (user_id = auth.uid() or public.kp_hauling_is_admin());

drop policy if exists "KP admins read due reminder sends" on public.kp_hauling_due_reminder_sends;
create policy "KP admins read due reminder sends"
on public.kp_hauling_due_reminder_sends for select
to authenticated
using (public.kp_hauling_is_admin());

-- Blank slate for KP Hauling tables only. Re-running this clears hauling app records,
-- drivers, availability, dumpsters, jobs, payments, expenses, and notifications.
truncate table
  public.kp_hauling_due_reminder_sends,
  public.kp_hauling_owner_notifications,
  public.kp_hauling_driver_cash_handoffs,
  public.kp_hauling_expenses,
  public.kp_hauling_job_payments,
  public.kp_hauling_job_charges,
  public.kp_hauling_jobs,
  public.kp_hauling_driver_availability_windows,
  public.kp_hauling_dumpsters
restart identity cascade;

delete from public.kp_hauling_profiles
where email <> 'admin@kp.local';

insert into public.kp_hauling_profiles (id, name, email, role, availability_status, availability_updated_at)
select id, 'KP Owner', email, 'owner', 'Available', now()
from auth.users
where lower(email) = 'admin@kp.local'
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  availability_status = excluded.availability_status,
  availability_updated_at = excluded.availability_updated_at,
  updated_at = now();
